### ISSUE TITLE
Helm command  for adding repo breaking

### ISSUE THREAD

**Issue by nathanbaleeta** [unicef/magasin#37]
Helm command  for adding repo [manually](https://unicef.github.io/magasin/install/) as below seems to be breaking 
```
helm repo add https://unicef.github.io/magasin/
```

**Comment by merlos** [comment]
Did you already added the repo using a different url (f.i using the installer with -u http://localhost:8000? If so you need to first delete the repo or use another name for the repo

**Comment by merlos** [comment]
Thanks!
The repo name was missing. Fixed!
